#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL2_gfx
Version  : 1.0.1
Release  : 1
URL      : http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz
Source0  : http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz
Summary  : drawing and graphical effects extension for SDL
Group    : Development/Tools
License  : Zlib
Requires: SDL2_gfx-lib
BuildRequires : SDL2-dev

%description
/*!
\mainpage SDL2_gfx - Graphics primitives and surface functions for SDL2
\section contact_sec Contact and License

%package dev
Summary: dev components for the SDL2_gfx package.
Group: Development
Requires: SDL2_gfx-lib
Provides: SDL2_gfx-devel

%description dev
dev components for the SDL2_gfx package.


%package lib
Summary: lib components for the SDL2_gfx package.
Group: Libraries

%description lib
lib components for the SDL2_gfx package.


%prep
cd ..
%setup -q -n SDL2_gfx-1.0.1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL2/SDL2_framerate.h
/usr/include/SDL2/SDL2_gfxPrimitives.h
/usr/include/SDL2/SDL2_imageFilter.h
/usr/include/SDL2/SDL2_rotozoom.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
